// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v5.29.3
// source: proto/alert/v1/alert.proto

package alertv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 为空表示订阅全部钢丝绳
	RopeIds []string `protobuf:"bytes,1,rep,name=rope_ids,json=ropeIds,proto3" json:"rope_ids,omitempty"`
	// 最低告警级别: 1=INFO 2=WARNING 3=CRITICAL
	MinLevel      int32 `protobuf:"varint,2,opt,name=min_level,json=minLevel,proto3" json:"min_level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_alert_v1_alert_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_v1_alert_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_proto_alert_v1_alert_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeRequest) GetRopeIds() []string {
	if x != nil {
		return x.RopeIds
	}
	return nil
}

func (x *SubscribeRequest) GetMinLevel() int32 {
	if x != nil {
		return x.MinLevel
	}
	return 0
}

type Alert struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlertId          string                 `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	RopeId           string                 `protobuf:"bytes,2,opt,name=rope_id,json=ropeId,proto3" json:"rope_id,omitempty"`
	Level            int32                  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"` // 1=INFO 2=WARNING 3=CRITICAL
	Message          string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	DamageFraction   float64                `protobuf:"fixed64,5,opt,name=damage_fraction,json=damageFraction,proto3" json:"damage_fraction,omitempty"` // Miner 累积损伤 D (1.0 = 失效)
	RemainingLifePct float64                `protobuf:"fixed64,6,opt,name=remaining_life_pct,json=remainingLifePct,proto3" json:"remaining_life_pct,omitempty"`
	OccurredAtUnix   int64                  `protobuf:"varint,7,opt,name=occurred_at_unix,json=occurredAtUnix,proto3" json:"occurred_at_unix,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_proto_alert_v1_alert_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_proto_alert_v1_alert_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_proto_alert_v1_alert_proto_rawDescGZIP(), []int{1}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetRopeId() string {
	if x != nil {
		return x.RopeId
	}
	return ""
}

func (x *Alert) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Alert) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Alert) GetDamageFraction() float64 {
	if x != nil {
		return x.DamageFraction
	}
	return 0
}

func (x *Alert) GetRemainingLifePct() float64 {
	if x != nil {
		return x.RemainingLifePct
	}
	return 0
}

func (x *Alert) GetOccurredAtUnix() int64 {
	if x != nil {
		return x.OccurredAtUnix
	}
	return 0
}

var File_proto_alert_v1_alert_proto protoreflect.FileDescriptor

const file_proto_alert_v1_alert_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/alert/v1/alert.proto\x12\balert.v1\"J\n" +
	"\x10SubscribeRequest\x12\x19\n" +
	"\brope_ids\x18\x01 \x03(\tR\aropeIds\x12\x1b\n" +
	"\tmin_level\x18\x02 \x01(\x05R\bminLevel\"\xec\x01\n" +
	"\x05Alert\x12\x19\n" +
	"\balert_id\x18\x01 \x01(\tR\aalertId\x12\x17\n" +
	"\arope_id\x18\x02 \x01(\tR\x06ropeId\x12\x14\n" +
	"\x05level\x18\x03 \x01(\x05R\x05level\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12'\n" +
	"\x0fdamage_fraction\x18\x05 \x01(\x01R\x0edamageFraction\x12,\n" +
	"\x12remaining_life_pct\x18\x06 \x01(\x01R\x10remainingLifePct\x12(\n" +
	"\x10occurred_at_unix\x18\a \x01(\x03R\x0eoccurredAtUnix2P\n" +
	"\fAlertService\x12@\n" +
	"\x0fSubscribeAlerts\x12\x1a.alert.v1.SubscribeRequest\x1a\x0f.alert.v1.Alert0\x01B.Z,crane-fatigue-monitor/proto/alert/v1;alertv1b\x06proto3"

var (
	file_proto_alert_v1_alert_proto_rawDescOnce sync.Once
	file_proto_alert_v1_alert_proto_rawDescData []byte
)

func file_proto_alert_v1_alert_proto_rawDescGZIP() []byte {
	file_proto_alert_v1_alert_proto_rawDescOnce.Do(func() {
		file_proto_alert_v1_alert_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_alert_v1_alert_proto_rawDesc), len(file_proto_alert_v1_alert_proto_rawDesc)))
	})
	return file_proto_alert_v1_alert_proto_rawDescData
}

var file_proto_alert_v1_alert_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_alert_v1_alert_proto_goTypes = []any{
	(*SubscribeRequest)(nil), // 0: alert.v1.SubscribeRequest
	(*Alert)(nil),            // 1: alert.v1.Alert
}
var file_proto_alert_v1_alert_proto_depIdxs = []int32{
	0, // 0: alert.v1.AlertService.SubscribeAlerts:input_type -> alert.v1.SubscribeRequest
	1, // 1: alert.v1.AlertService.SubscribeAlerts:output_type -> alert.v1.Alert
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_alert_v1_alert_proto_init() }
func file_proto_alert_v1_alert_proto_init() {
	if File_proto_alert_v1_alert_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_alert_v1_alert_proto_rawDesc), len(file_proto_alert_v1_alert_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_alert_v1_alert_proto_goTypes,
		DependencyIndexes: file_proto_alert_v1_alert_proto_depIdxs,
		MessageInfos:      file_proto_alert_v1_alert_proto_msgTypes,
	}.Build()
	File_proto_alert_v1_alert_proto = out.File
	file_proto_alert_v1_alert_proto_goTypes = nil
	file_proto_alert_v1_alert_proto_depIdxs = nil
}
